// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3eBIV8ANqzkszWF2oTe8VQ6DWFdPIeNo',
    appId: '1:1055944097838:web:083e6cbe4f85961eb41fbf',
    messagingSenderId: '1055944097838',
    projectId: 'fir-flutter-13cb4',
    authDomain: 'fir-flutter-13cb4.firebaseapp.com',
    storageBucket: 'fir-flutter-13cb4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAceaFxsxqP7qwnYpZrY5L4WrSCduOXgyI',
    appId: '1:1055944097838:android:734524df53ac7fd8b41fbf',
    messagingSenderId: '1055944097838',
    projectId: 'fir-flutter-13cb4',
    storageBucket: 'fir-flutter-13cb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX7oymptgsdAUjn3KE1SUxqkpWLeOhLO4',
    appId: '1:1055944097838:ios:3ebf217690f8dd66b41fbf',
    messagingSenderId: '1055944097838',
    projectId: 'fir-flutter-13cb4',
    storageBucket: 'fir-flutter-13cb4.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX7oymptgsdAUjn3KE1SUxqkpWLeOhLO4',
    appId: '1:1055944097838:ios:3ebf217690f8dd66b41fbf',
    messagingSenderId: '1055944097838',
    projectId: 'fir-flutter-13cb4',
    storageBucket: 'fir-flutter-13cb4.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3eBIV8ANqzkszWF2oTe8VQ6DWFdPIeNo',
    appId: '1:1055944097838:web:5dce73bdd4359740b41fbf',
    messagingSenderId: '1055944097838',
    projectId: 'fir-flutter-13cb4',
    authDomain: 'fir-flutter-13cb4.firebaseapp.com',
    storageBucket: 'fir-flutter-13cb4.firebasestorage.app',
  );
}
